### ISSUE TITLE
Scenario erreur graphique de lien

### ISSUE THREAD

**Issue by guenneguezt** [jeedom/plugin-blea#25]
Bonjour,

Comme toi j'utilises les sous class pour mon plugin ipx800. J'ai un souci lorsque je vais sur un scenario pour voir les dépendances.
J'ai fait un ticket à l'équipe jeedom :
https://github.com/jeedom/issues/issues/259
Comme tu verras Loic me dit que mon erreur est lié à mon plugin et de voir comment tu as implémenté.
Je ne vois pas de différence avec toi mis à par que moi les classes sont dans des sous fichiers.
C'est je pense plus lisible.

Peux-tu me dire si toi aussi l'accès au graphique des liens fonctionne avec ton plugin, je n'ai pas cette techno pour tester ?

Si ça fonctionne, as-tu fait quelque chose de particulier dans ton code ?

Merci d'avance
Thomas

**Comment by sarakha63** [comment]
La différence entre blea, jeelink calendar qui utilsies des sous classes, c'est que ce ne sont pas des sous classes d'équipements. Dans ton cas tu as des équipements qui appartiennent a des classes différentes pour le même plugin.
Il faudrait je pense qu'un jour tu prennes le temps de faire en sorte que tous tes équipemenets soit de la classe IPX même les sous éléments mais que ce soit un attribut de configuration de l'eqlogic qui permette de cibler leur famille (la majorité des plugins font comme ça). Ca sera beaucoup plus simple pour toi et surtout tu auras pas ce genre de désagrément que tu as depuis longtemps même si jusqua present ya toujours eu un moyen de s'en sortir pour toi

      De : guenneguezt <notifications@github.com>
 À : jeedom/plugin-blea <plugin-blea@noreply.github.com> 
Cc : Subscribed <subscribed@noreply.github.com>
 Envoyé le : Vendredi 21 juillet 2017 17h56
 Objet : [jeedom/plugin-blea] Scenario erreur graphique de lien (#25)
   
Bonjour,Comme toi j'utilises les sous class pour mon plugin ipx800. J'ai un souci lorsque je vais sur un scenario pour voir les dépendances.
J'ai fait un ticket à l'équipe jeedom :
jeedom/issues#259
Comme tu verras Loic me dit que mon erreur est lié à mon plugin et de voir comment tu as implémenté.
Je ne vois pas de différence avec toi mis à par que moi les classes sont dans des sous fichiers.
C'est je pense plus lisible.Peux-tu me dire si toi aussi l'accès au graphique des liens fonctionne avec ton plugin, je n'ai pas cette techno pour tester ?Si ça fonctionne, as-tu fait quelque chose de particulier dans ton code ?Merci d'avance
Thomas—

**Comment by guenneguezt** [comment]
Bonjour,

C'est ce que je me dis, mais c'est un boulot monstre d'autant plus que je ne suis pas le seul a utiliser ce mode.
En plus, il faudrait gérer delà de façon transparente pour les utilisateurs et autre, et je ne vois même pas par où commencer.

A+
Thomas

**Comment by lunarok** [comment]
Tu n'es pas le seul ? Ah bon, pourtant a chaque fois t'es le seul avec le problème. Ça fait de nombreux mois quand meme que ta structuration pose des soucis. Alors oui ça te demanderais du boulot de revenir au standard, mais chaque fois ne le faisant pas tu impact loic/sarakha63 pour bosser pour toi seul. Sans compter que du coup les bouts de scotch ajoutes pour gère ton format ne peuvent pas améliorer les perfs de jeedom.
Donc oui, le mieux ça serait que tu mettes tes plugins au format courant, t'auras moins de soucis et on pourra garder et un jeedom focalisé et véloce.

**Comment by guenneguezt** [comment]
Bonjour,

Lunarok, tu pourrais mettre un peu de nuances dans tes propos...
D'abord, le standard, peux-tu me dire où il est décris, je m'y réfèrerais sans problème.
Le plugin le plus ancien que j'ai créé sur ce model date d'avant décembre 2014... Donc effectivement j'utilise un mode qui n'est pas celui que tout le monde utilise, mais de là à dire qu'il n'est pas standard, il y a une grosse différence. Après ne surtout pas prendre celà pour une critique sur la doc, je suis aussi allergique à la rédaction de doc que Loïc.

Pour le tu n'es pas le seul, 2 choses :
1) Il existe aussi par exemple :
protexiom de fdp1.
vigilancemeteo de lunarok. Tient toi aussi tu ne respecte pas le standard
arrosage de psykok.
2) Ce n'est pas parce que je suis le seul à remonter un bug que celui-ci n'existe pas.

A+
Thomas

**Comment by guenneguezt** [comment]
Bonjour,

Lunarok, tu pourrais mettre un peu de nuances dans tes propos...
D'abord, le standard, peux-tu me dire où il est décris, je m'y réfèrerais sans problème.
Le plugin le plus ancien que j'ai créé sur ce model date d'avant décembre 2014... Donc effectivement j'utilise un mode qui n'est pas celui que tout le monde utilise, mais de là à dire qu'il n'est pas standard, il y a une grosse différence. Après ne surtout pas prendre celà pour une critique sur la doc, je suis aussi allergique à la rédaction de doc que Loïc.

Pour le tu n'es pas le seul, 2 choses :
1) Il existe aussi par exemple :
protexiom de fdp1.
vigilancemeteo de lunarok. Tient toi aussi tu ne respecte pas le standard
arrosage de psykok.
2) Ce n'est pas parce que je suis le seul à remonter un bug que celui-ci n'existe pas.

A+
Thomas

**Comment by lunarok** [comment]
Qu'est-ce que vient faire là vigilancemeteo ? T'as vu des sous-classes dedans ? Tu as lu la remarque de @sarakha63 qui te dit qu'on utilise un type pour différencier les équipements avec un fonctionnement différent ? Parceque c'est exactement ce que fait le plugin.
Des changements côté core/chartre qui nécessitent de se retrousser les manches sur les plugins tiers, y en a eu un paquet. C'est pas drôle mais ca fait partie du boulot. Les bootstrap, la mise en place en core des dépendances, pareil pour les services, les batteries, la gestion du ask ...
Bref, c'est faire le suivi de ses plugins en restant dans les standards Jeedom ET ce qui est mieux aussi pour les utilisateurs (et demander des sparadraps pour pas modifier son code, c'est pas cool pour les users)

Pour la doc des changements, réponse à la loic : y a les commits :)

**Comment by sarakha63** [comment]
Tu mélanges  plusieurs choses. Gérer plusieurs type d'équipement comme.le.font un bon paquet de plugins ne veut pas dire sous classe. Il n'y a pas de sous classe dans blea pour les équipements ni aucun plugin protocolaire. Ni même vigilance météo que tu prends en exemple

**Comment by guenneguezt** [comment]
Bonjour,

Effectivement pour vigilancemeteo, c'est une erreur de ma part, mais avant il contenait des sous class car les fichiers crues.class.php  maree.class.php  previsionpluie.class.php existent encore dans mon arborescence de jeedom.

A+
Thomas

**Comment by lunarok** [comment]
De mémoire, c'est les backup des anciens fichiers des plugins mergés. Donc aucune utilité, ils n'ont jamais été appelé du plugin. Une sous classe ne se déduit pas de la présence d'un fichier dans l'arborescence.

**Comment by guenneguezt** [comment]
Bonjour,

Je souhaite basculer mes plugins pour ne plus être embêter avec mon fonctionnement atypique.
J'ai donc dans le post initial ajouté la méthode que je compte suivre.
https://github.com/jeedom/issues/issues/259#issuecomment-319821990
Je ne sais pas si Loic aura le temps de regarder, mais si vous avez le temps, pouvez-vous m'indiquer ce que vous en pensez ?

A+
Thomas
